# ubuntu 16.04 with node 14.17.4
FROM dbsites/ubuntu-ethiq

# Working directory for application
WORKDIR /usr/src/app

# Arguments given by scripts/staging.sh or scripts/deploy.sh
ARG DATABASE_MIGRATIONS
ARG DATABASE_SCOPES

# Set Environment Variables from Arguments
ENV DB_MIGRATIONS=${DATABASE_MIGRATIONS}
ENV DB_SCOPES=${DATABASE_SCOPES}

# Install db-migrate
RUN npm install db-migrate db-migrate-pg -g

# npm install into /usr/src/app
# A wildcard is used to ensure both package.json AND package-lock.json are copied
COPY package*.json /usr/src/app/
RUN npm install

# copy webapp files to container & build:prod
COPY . /usr/src/app/
RUN npm run build:prod

# replace this with your application's default port
EXPOSE 3000

# run migrations and start server in container
CMD ["/bin/bash", "-c", "./scripts/start-prod-app.sh ${DB_MIGRATIONS} ${DB_SCOPES}"]